import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import { NavDesktop } from '@/components/Nav-desktop'
import { NavMobile } from '@/components/Nav-Mobile'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'LEARNING TS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <NavMobile />
        {children}
        <Footer />
        </body>
    </html>
  )
}
